import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { IDKitWidget } from "@worldcoin/idkit";
import type { ISuccessResult } from "@worldcoin/idkit";
import { BigNumber, ethers } from "ethers";
import { useSigner, useNetwork, useAccount } from "wagmi";
import { KizunaAbi } from "../lib/abi";
import { ERC20ABI } from "../lib/ERC20abi";
import { contractAddress } from "../lib/web3";
import { USDCContractAddress } from "../lib/web3";
import React, { useEffect, useState, useCallback } from "react";

// import {
//   LoginButton,
//   WhenLoggedInWithProfile,
// } from "../../archives/components/index_archive";

import {
  Heading,
  Box,
  Button,
  ButtonGroup,
  IconButton,
  Container,
  Text,
  Link,
  Flex,
  Spacer,
  Table,
  TableContainer,
  TableCaption,
  Thead,
  Tr,
  Th,
  Td,
  Tbody,
  HStack,
  Image,
  useBreakpointValue,
  Center,
  Stack,
  Input,
} from "@chakra-ui/react";
import NextLink from "next/link";

const Home: NextPage = () => {
  const [amount, setAmount] = useState("");
  const { data: signer } = useSigner();

  const handleAmountChange = (e: any) => {
    const inputValue = e.target.value;
    setAmount(inputValue);
  };

  const repayLoan = async (requestId: string) => {
    if (!signer) return;
    const overrides = {
      gasLimit: ethers.utils.hexlify(200000),
    };
    const USDCcontract = new ethers.Contract(
      USDCContractAddress,
      ERC20ABI,
      signer
    );
    console.log("Approving USDC");
    const aptx = await USDCcontract.approve(contractAddress, amount, overrides);
    console.log(aptx);
    const contract = new ethers.Contract(contractAddress, KizunaAbi, signer);
    const tx = await contract.repayLoan(requestId, amount);
    console.log(tx.hash);
  };

  const liquidateCollateral = async (requestId: string) => {
    if (!signer) return;
    const contract = new ethers.Contract(contractAddress, KizunaAbi, signer);
    const tx = await contract.liquidateCollateral(requestId);
    console.log(tx.hash);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <header className={styles.header}>
        <Box as="section" pb={{ base: "12", md: "24" }} p="3">
          <Box as="nav" bg="bg-surface" boxShadow="sm">
            <Flex>
              <Button as="a" href="/">
                KIZUNA Protocol
              </Button>
              <Spacer></Spacer>
              <ConnectButton />
            </Flex>
            <Container py={{ base: "4", lg: "5" }}>
              <HStack spacing="5" justify="space-between">
                <Flex justify="center" flex="1">
                  <ButtonGroup variant="link" spacing="100">
                    <Link href="/list">
                      <Button>List</Button>
                    </Link>
                    <Link href="/createloan">
                      <Button>Create Loan</Button>
                    </Link>
                    <Link href="/yourpool">
                      <Button colorScheme="black" variant="outline">
                        Your Pool
                      </Button>
                    </Link>
                  </ButtonGroup>
                </Flex>
              </HStack>
            </Container>
          </Box>
        </Box>
      </header>

      {/* <LoginButton />
      <WhenLoggedInWithProfile>
        {({ profile }) => <div>{`Welcome @${profile.handle}`}</div>}
      </WhenLoggedInWithProfile> */}
      <Heading p="3">
        <Text>Your Lending</Text>
      </Heading>
      <TableContainer>
        <Table variant="simple">
          <Thead>
            <Tr>
              <Th>Image</Th>
              <Th>Asset</Th>
              <Th>Amount</Th>
              <Th>Collateral</Th>
              <Th>APY</Th>
              <Th>DueDate</Th>
            </Tr>
          </Thead>
          <Tbody>
            <Tr>
              <Td>
                <Image
                  src="./usd-coin-usdc-logo.png"
                  boxSize="50px"
                  alt="Dan Abramov"
                />
              </Td>
              <Td>USDC</Td>
              <Td>72.85</Td>
              <Td>75.4%</Td>
              <Td>20%</Td>
              <Td>2023-06-31</Td>
            </Tr>
            <Tr>
              <Td>
                <Image
                  src="./usd-coin-usdc-logo.png"
                  boxSize="50px"
                  alt="Dan Abramov"
                />
              </Td>
              <Td>USDC</Td>
              <Td>72.85</Td>
              <Td>75.4%</Td>
              <Td>20%</Td>
              <Td>2023-06-31</Td>
            </Tr>
            <Tr></Tr>
          </Tbody>
        </Table>
      </TableContainer>
      <Heading p="3">
        <Text>Your Borrowing</Text>
      </Heading>

      <TableContainer>
        <Table variant="simple">
          <Thead>
            <Tr>
              <Th>Image</Th>
              <Th>Asset</Th>
              <Th>Amount</Th>
              <Th>Collateral</Th>
              <Th>APY</Th>
              <Th>DueDate</Th>
              <Th>Repay Amount</Th>
              <Th>Repay</Th>
            </Tr>
          </Thead>
          <Tbody>
            <Tr>
              <Td>
                <Image
                  src="./usd-coin-usdc-logo.png"
                  boxSize="50px"
                  alt="Dan Abramov"
                />
              </Td>
              <Td>USDC</Td>
              <Td>72.85</Td>
              <Td>75.4%</Td>
              <Td>20%</Td>
              <Td>2023-06-31</Td>
              <Td>
                <Input placeholder="Send Amount (ex)10.7" />
              </Td>
              <Td>
                <Button as="a" href="/">
                  Repay Your USDC
                </Button>
              </Td>
            </Tr>
            <Tr>
              <Td>
                <Image
                  src="./usd-coin-usdc-logo.png"
                  boxSize="50px"
                  alt="Dan Abramov"
                />
              </Td>
              <Td>USDC</Td>
              <Td>72.85</Td>
              <Td>75.4%</Td>
              <Td>20%</Td>
              <Td>2023-06-31</Td>
              <Td>
                <Input placeholder="Send Amount (ex)10.7" />
              </Td>
              <Td>
                <Button as="a" href="/">
                  Repay Your USDC
                </Button>
              </Td>
            </Tr>
            <Tr></Tr>
          </Tbody>
        </Table>
      </TableContainer>
    </div>
  );
};

export default Home;
